library(data.table)
library(DT)
library(forcats)
library(ggplot2)
library(haven)
library(Hmisc)
library(plotly)
library(scales)
library(shiny)
library(stringi)
library(dplyr)
library(rsconnect)
library(dplyr)
library(ggplot2)
library(caret)
library(class)
library(GGally)
library(e1071)
library(naivebayes)
library(tidyr)
library(ggpubr)
library(data.table)
library(readr)  # for read_csv
library(knitr)  # for kable
library(RCurl)

PoliceUrl ="https://raw.githubusercontent.com/dawsond-smu/Analytics/master/PoliceBrutality/PoliceKillingsUS.csv"
Police <-read_csv(url(PoliceUrl))
head(Police)